[author]
  # name = "Your name here"
  # image = "/img/author.jpg"
  # email = "hello@your_domain.com"

  # twitter = "https://twitter.com/username"
  # github = "https://github.com/username"
  # keybase = "https://keybase.io/username"
  # linkedin = "https://linkedin.com/in/username/"
