# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the README for more details about each of these parameters.

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showReadingTime = true
  showHeadingAnchors = true
  showAuthor = true
  showPagination = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"
