languageCode = "ja"
languageName = "日本語"
languageDirection = "ltr"
weight = 2

title = "Congo"
copyright = "&copy; 2023 Congo contributors"

[params]
  dateFormat = "2006年1月2日"

  mainSections = ["samples"]
  description = "Tailwind CSSをベースに開発された強力で軽量なHugo向けテーマ"
