languageCode = "es-MX"
languageName = "Español (México)"
languageDirection = "ltr"
weight = 2

title = "Congo"
copyright = "&copy; 2023 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "Un tema poderoso y liviano para Hugo creado con Tailwind CSS."
