languageCode = "de-DE"
languageName = "Deutsch (Deutschland)"
languageDirection = "ltr"
weight = 4

title = "Congo"
copyright = "&copy; 2023 Congo contributors"

[params]
  dateFormat = "2. January 2006"

  mainSections = ["samples"]
  description = "Ein leistungsstarkes, leichtgewichtiges Theme für Hugo, das mit Tailwind CSS erstellt wurde."

