name: Commit Messages
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Gitmoji
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: ^[\u0020-\u007e\u00a0-\u00ff\u0152\u0153\u0178]+'
          flags: "g"
          error: "Commit messages must start with a Gitmoji character."
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}
