name: GitHub Pages

on:
  push:
    branches:
      - stable

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        working-directory: ./exampleSite
        run: hugo --minify --themesDir ../.. --baseURL https://jpanther.github.io/Congo/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./exampleSite/public
